version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - BASE_URL=http://localhost:3000
    volumes:
      - ./public/images:/usr/src/app/public/images
