version: '3'
services:
  app:
    # 使用当前目录的Dockerfile构建容器镜像
    build: .
    ports:
      # 将容器内部的3000端口映射到主机的3000端口
      - "3000:3000"
    environment:
      # 设置应用程序运行的端口
      - PORT=3000
      # 设置应用程序的基础URL，用于本地开发
      - BASE_URL=http://localhost:3000
      # 设置用于复制链接的公共URL，需要替换为实际的域名
      - COPY_URL=http://your-public-domain.com
    volumes:
      # 将主机的./public/images目录挂载到容器内的/usr/src/app/public/images
      # 这样可以在容器外部管理和持久化图片文件
      - ./public/images:/usr/src/app/public/images

# 注意：
# 1. 确保Dockerfile存在于当前目录中，并正确配置了应用程序的构建过程
# 2. 在生产环境中，应该使用实际的公共域名替换COPY_URL的值
# 3. 端口映射(3000:3000)
